### PR TITLE
BSON is better for ROS#

### PR DESCRIPTION
**Pull request by akirayou**
rosbridge is now (0.11.0 or later) supports Inf and NaN float data on bson_only_mode.
https://github.com/RobotWebTools/rosbridge_suite/pull/391
It's useful for LaserScan data (It often contains Nan or Inf float data).
And also BSON is also little bit faster on binary data such as PointCloud.

I just overwrite Serialize/Deserialize function,So you can not use JSON any more.
So in this Patch,you have to launch rosbridge  with bson_only_mode flag.
Like this.
<launch>
	<include file="$(find rosbridge_server)/launch/rosbridge_websocket.launch">
		<arg name="port" value="9090"/>
		<arg name="bson_only_mode" value="true"/>
	</include>
</launch>

### CODE REVIEW

**Comment by MartinBischoff** [comment]
Thanks @akirayou , this is nice.
Having a BSON (de-) serialization make sense as we already discussed in #136.
However I would not want to completely replace JSON by BSON in the ROS# master branch.
There are also reasons to use JSON and I think best would be to have both options, with JSON as default.

So I'd suggest to change the `Serialize` method as follows (`Deserialize` analogous):
```
private static byte[] Serialize<T>(T obj, bool UseJson = true)
{
    if (UseJson)
      // existing code
    if (UseBson)
       // your Bson serialization
}
````
Does this make sense to you?

I also find your contirbution / modifications worth mentioning in the file's header. So would you please add a comment like:
```
// Adding BSON (de-)seriliazation option
// <your affilitation>, 2019, <your name> (your e-mail / github account)
``` 
one line below the header of each source file that you change, similar to as we did [here](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/RosCommuncation/ImagePublisher.cs)?

Thank you!

**Comment by MartinBischoff** [comment]
Right. Please add the options to RosConnector and RosSocket, that's a lot better.

**Comment by akirayou** [comment]
I add the code ,selecting serializer.

I remove "static"  on Serializer/Desirializer to pass the member variable "Serializer".
If you dislike this workaround I can rewrite by another way.  (i.e. Pass it by the function's argument.)

And I used enum instead of bool.  Because my friend says "MsgPack is faster!!".  

Thank you

**Comment by MartinBischoff** [comment]
That is beautiful, thank you.

The only thing left to do is updating [Unity3D/Assets/RosSharp/Plugins.RosBridgeClient.dll](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Plugins/RosBridgeClient.dll) with you new compiled version.

I will then merge your pull request.

**Comment by akirayou** [comment]
Oh,I forgot it.
Done! Thank you.

**Pull request merged**
